specVersion: 1.0.0
name: slp-moonriver-subql
version: 1.0.0
runner:
  node:
    name: "@subql/node"
    version: "*"
  query:
    name: "@subql/query"
    version: "*"
description: This SubQuery project can be use as a starting point for bifrost network
repository: "https://github.com/bifrost-finance/slp-moonriver-subql"
schema:
  file: ./schema.graphql
network:
  chainId: "0x401a1f9dca3da46f5c4091016c8a2f26dcea05865116b286f60f668207d1474b"
  endpoint: "wss://public-rpc.pinknode.io/moonriver"
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 2146518
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: staking
          kind: substrate/BlockHandler
        - handler: handleStakingErapaid
          kind: substrate/EventHandler
          filter:
            module: parachainStaking
            method: NewRound
        - handler: handleRemarked
          kind: substrate/EventHandler
          filter:
            module: system
            method: Remarked
