specVersion: 0.2.0
name: slp-moonriver-subql
version: 1.0.0
description: ''
repository: 'https://github.com/bifrost-finance/slp-kusama-subql.git'
schema:
  file: ./schema.graphql
network:
  genesisHash: '0x401a1f9dca3da46f5c4091016c8a2f26dcea05865116b286f60f668207d1474b'
  endpoint: 'wss://moonriver.api.onfinality.io/public-ws'
  chaintypes:
    file: './dist/chaintypes.js'
dataSources:
  - kind: substrate/Runtime
    startBlock: 1900000
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: staking
          kind: substrate/BlockHandler
        - handler: handleStakingErapaid
          kind: substrate/EventHandler
          filter:
            module: parachainStaking
            method: NewRound
        - handler: handleRemarked
          kind: substrate/EventHandler
          filter:
            module: system
            method: Remarked
