specVersion: 0.2.0
name: slp-moonriver-subql
version: 1.0.0
description: ''
repository: 'https://github.com/bifrost-finance/slp-kusama-subql.git'
schema:
  file: ./schema.graphql
network:
  genesisHash: '0xd90bc3c5a0f687a755fc8731a0fdc4ec4c0d807f7ae969530980280515c4bfa9'
  endpoint: 'wss://moonriver-rpc.devnet.liebi.com/ws'
  chaintypes:
    file: './dist/chaintypes.js'
dataSources:
  - kind: substrate/Runtime
    startBlock: 8900
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: staking
          kind: substrate/BlockHandler
        - handler: handleStakingErapaid
          kind: substrate/EventHandler
          filter:
            module: parachainStaking
            method: NewRound
        - handler: handleRemarked
          kind: substrate/EventHandler
          filter:
            module: system
            method: Remarked
